name: CI

on:
  push:
    branches: [ second ]
  pull_request:
    branches: [ second ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code from repository
      uses: actions/checkout@v3

    - name: Restore NuGet packages
      run: nuget restore observatory.sln

    - name: Build project using MSBuild
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" observatory.sln /p:Configuration=Release