name: CI

on:
  push:
    branches: [ second ]
  pull_request:
    branches: [ second ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code from repository
      uses: actions/checkout@v3

    - name: Restore NuGet packages
      run: nuget restore observatory.sln

    - name: Build project using MSBuild
      run: msbuild observatory.sln /p:Configuration=Release

    - name: Clean build artifacts (optional)
      run: |
        if (Test-Path "observatory/bin/Release") { echo "Build succeeded, release binaries generated." }