name: CI

on:
  push:
    branches: [ second ]
  pull_request:
    branches: [ second ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Проверка кода из репозитория
      uses: actions/checkout@v3

    - name: Установка .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Билд проекта
      run: dotnet build --configuration Release --no-restore

    - name: Запуск тестов
      run: dotnet test --no-build --verbosity normal