name: CI

on:
  push:
    branches: [ second ]
  pull_request:
    branches: [ second ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checking code from repository
      uses: actions/checkout@v3

    - name: Download .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'
    - name: Restore NuGet packages
      run: nuget restore observatory.sln
    - name: Restore dependencies
      run: dotnet restore observatory.sln

    - name: Project build
      run: dotnet build observatory.sln --configuration Release --no-restore

    - name: Starting test
      run: dotnet test observatory/observatory.csproj --no-build --verbosity normal