jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install MSBuild
      run: |
        choco install visualstudio2019buildtools -y --version=16.11.2
        choco install visualstudio2022buildtools -y --version=17.5.4
        refreshenv

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: 'latest'

    - name: Restore NuGet packages
      run: nuget restore observatory.sln

    - name: Build with MSBuild
      run: msbuild observatory.sln /p:Configuration=Release